name: golangci-lint

concurrency:
  group: pr-go-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Commit SHA or tag to check out"
        required: true
        type: string

permissions:
  contents: read

jobs:
  golangci:
    name: Tests and Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout porter-dev/porter at ${{ github.event.inputs.tag }}
        uses: actions/checkout@v4
        with:
          repository: porter-dev/porter
          ref: ${{ github.event.inputs.tag }}
          token: ${{ secrets.PORTERSUPPORT_GITHUB_TOKEN }}
          fetch-tags: true
          fetch-depth: 0

      - name: Get changed go files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            *.go
            *.mod
            *.sum
            **/*.go
            **/*.mod
            **/*.sum

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - uses: actions/setup-go@v4
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          go-version-file: go.mod
      - name: Go Tests
        if: steps.changed-files.outputs.any_changed == 'true'
        run: go test -v ./...
      - name: golangci-lint
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: -c .github/golangci-lint.yaml --verbose
          skip-pkg-cache: true
          only-new-issues: true # this is needed until the following is merged: https://github.com/golangci/golangci-lint-action/issues/820

