name: Release Porter CLI
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the release"
        required: true
        type: string

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
      - name: Checkout porter-dev/porter at ${{ github.event.inputs.tag }}
        uses: actions/checkout@v4
        with:
          repository: porter-dev/porter
          ref: ${{ github.event.inputs.tag }}
          token: ${{ secrets.PORTERSUPPORT_GITHUB_TOKEN }}
          fetch-tags: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      # m1 runners do not come with docker natively installed
      - name: Install Docker on macOS
        if: runner.os == 'macOS'
        run: |
          brew install --cask docker
          brew install colima docker-buildx
          colima start

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: v2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PORTERSUPPORT_GITHUB_TOKEN }}
