name: Release Porter Agent
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Commit SHA or tag to check out"
        required: true
        type: string

permissions:
  contents: write

env:
  # WORK_DIR is the directory where the go.mod file is located, and goreleaser will be run from
  WORK_DIR: agent
  # TAG_PREFIX is the prefix of the tag that should be removed before passing to goreleaser
  TAG_PREFIX: agent/

jobs:
  goreleaser:
    runs-on: ubicloud-standard-8
    steps:
      - name: Checkout porter-dev/porter at ${{ github.event.inputs.tag }}
        uses: actions/checkout@v4
        with:
          repository: porter-dev/code
          ref: ${{ github.event.inputs.tag }}
          token: ${{ secrets.PORTERSUPPORT_GITHUB_TOKEN }}
          fetch-tags: true
      - name: Remove tag prefix
        run: |
          echo TAG_WITHOUT_PREFIX=$(sed 's|${{ env.TAG_PREFIX }}||g' <<< ${{ github.event.inputs.tag }} ) >> $GITHUB_ENV
          echo $TAG_WITHOUT_PREFIX

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ env.WORK_DIR }}/go.mod

      - name: Docker logins
        run: echo $GITHUB_TOKEN | docker login ghcr.io -u USERNAME --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.PORTERSUPPORT_GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          workdir:  ${{ env.WORK_DIR }}
          distribution: goreleaser
          version: v2
          args: release --clean --parallelism=4
        env:
          GITHUB_TOKEN: ${{ secrets.PORTERSUPPORT_GITHUB_TOKEN }}
          GORELEASER_CURRENT_TAG: ${{ env.TAG_WITHOUT_PREFIX }}
