name: Test install script on all platforms

on:
  workflow_dispatch:
    inputs: {}

permissions:
  contents: read

jobs:
  tests:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubicloud-standard-4
          - ubicloud-standard-4-arm
          - macos-latest
    name: Test install script on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Export runner info
        run: |
          uname
          arch
      - name: Setup porter
        uses: porter-dev/setup-porter@v0.1.0
      - name: Deploy stack
        timeout-minutes: 30
        run: exec porter version
